### ISSUE TITLE
Unable to build on Ubuntu 13.04 x86_64

### ISSUE THREAD

**Issue by Pferd** [Adaptv/ribs2#4]
Hi, I'm newbie to  c/c++ programming and trying to learn. Ribs,  after being found on some Internet site and going through read me, felt like trying it. I was stuck right at the beginning. I tried to get the clone of the project and just made a simple make. However, its throwing this error.

../include/ribs.h:29:24: fatal error: thashtable.h: No such file or directory
compilation terminated.
make[2]: **\* [../obj/ribify.o] Error 1
make[1]: **\* [buildall] Error 2
make: **\* [all] Error 2

I couldn't find much information concerning thashtable. Can someone please help me?
