### ISSUE TITLE
Can't compile on 12.04

### ISSUE THREAD

**Issue by voidwisp** [Adaptv/ribs2#2]
Tried to follow the tutorial on Ubuntu 12.04. Couldn't compile it. First the mysql.h is in in /usr/include/mysql.h not /usr/include/mysql/mysql.h .. When it fixed that it still wouldn't compile as the mysqldump example was failing on the ribify step.. with these errors: 

(LD)     mydumper  [ -o ../bin/mydumper ../obj/mydumper.o  -L ../../../lib -lribs2 -lribs2_mysql -L../ribified -pthread -lribs2_mysql -lmysqlclient -lm -lz -ldl -L../../ribs2/lib -lribs2 -L../lib ]
../ribified/libmysqlclient.a(client.c.o): In function `mysql_close_free_options':
(.text+0x2ea): undefined reference to`SSL_CTX_free'

Had to remove them from compilation..
